//Auth token we will use to generate a meeting and connect to it
const authToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiJhZjM3Y2I2Ny03MjM3LTRkNDItOGU1ZS1jNzUxODU4ZTdlYjEiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTcxMzYyMzQyOCwiZXhwIjoxODcxNDExNDI4fQ.q3e634x1ETzP1AOtOw0fMfvunJnQlP2jyY7mtl9srWM";

export { authToken };