name: Deploy to GCP
run-name: ${{ github.actor }} has triggered a deployment 🚀
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: sh scripts/init.sh
      - name: Build and dockerize
        run: sh scripts/build.sh
      - name: Configure Docker credentials
        uses: docker/login-action@v1
        with:
          registry: europe-west1-docker.pkg.dev/sopra-fs24-group-22/let-them-cook
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Push Docker image
        run: |
          docker tag let-them-cook:latest europe-west1-docker.pkg.dev/sopra-fs24-group-22/let-them-cook/let-them-cook:${{ github.sha }}
          docker push europe-west1-docker.pkg.dev/sopra-fs24-group-22/let-them-cook/let-them-cook:${{ github.sha }}
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy let-them-cook \
            --image europe-west1-docker.pkg.dev/sopra-fs24-group-22/let-them-cook/let-them-cook:${{ github.sha }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
